In [1]:
my_list=[1,2,3]

In [2]:
import numpy as np

In [3]:
arr=np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones(4)

array([1., 1., 1., 1.])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.random.rand(5)

array([0.44012494, 0.48609647, 0.99650906, 0.02488061, 0.57219748])

In [18]:
np.random.rand(5,5)

array([[0.87639567, 0.89976712, 0.83126964, 0.14540325, 0.36841056],
       [0.34054555, 0.2718526 , 0.24806232, 0.83470969, 0.56598044],
       [0.24367886, 0.93466982, 0.27241249, 0.4623485 , 0.38695613],
       [0.63700207, 0.41127079, 0.53837099, 0.69920511, 0.70438234],
       [0.0752052 , 0.86062739, 0.98964706, 0.50089792, 0.65074522]])

In [19]:
np.random.randn(2)

array([0.26349732, 0.06681305])

In [21]:
np.random.randint(1,100,10)

array([65, 88, 81, 38, 16, 26, 73, 31, 22, 84])