In [7]:
import numpy as np

In [32]:
arr_2d=np.array([[5,12,23],[3,4,5],[7,8,9]])

In [34]:
arr_2d

array([[ 5, 12, 23],
       [ 3,  4,  5],
       [ 7,  8,  9]])

In [35]:
arr_2d[0][0]

5

In [36]:
arr_2d[:2,1:]

array([[12, 23],
       [ 4,  5]])

In [38]:
arr_2d[1: ,0:2]

array([[3, 4],
       [7, 8]])

In [39]:
arr_2d[:2]

array([[ 5, 12, 23],
       [ 3,  4,  5]])

In [40]:
arr=np.arange(1,11)

In [41]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
bool_arr=arr>5

In [44]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [45]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [46]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [47]:
arr[arr<4]

array([1, 2, 3])

In [48]:
arr_2d=np.arange(50).reshape(5,10)

In [49]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [51]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [53]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])